## Задание 1
#### Импортируйте библиотеку Numpy и дайте ей псевдоним np.

In [1]:
import numpy as np

#### Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [29]:
a=np.array(
    [[1,6],
    [2,8],
    [3,11],
    [3,10],
    [1,7]]
    );


mean_a = np.array([])
for k,i in enumerate(a[0]):
    mean_a = np.append(mean_a,a[:,k].mean())

mean_a

array([2. , 8.4])

## Задание 2
#### Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [30]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3
#### Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [54]:
a_centered_sp = np.dot(a_centered.T[0],a_centered.T[1])
print(a_centered_sp)
b = len(a)-1
print(b)
print(f'{(a_centered_sp/b)}')

8.0
4
2.0


## Задание 4**
#### В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [48]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

# Тема “Работа с данными в Pandas”
## Задание 1
#### Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский']. Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:
#### [1, 1, 1, 2, 2, 3, 3], 
#### ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
#### [450, 300, 350, 500, 450, 370, 290].


In [58]:
import pandas as pd

In [64]:
authors = pd.DataFrame();
authors['author_id'] = [1, 2, 3];
authors['author_name'] = ['Тургенев', 'Чехов', 'Островский'];

book = pd.DataFrame();
book['author_id'] = [1, 1, 1, 2, 2, 3, 3];
book['book_title'] = ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'];
book['price'] = [450, 300, 350, 500, 450, 370, 290];

## Задание 2
#### Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [114]:
authors_price = pd.merge(authors,book,how = 'inner', on = 'author_id');
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Задание 3
#### Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [113]:
top5 = authors_price.nlargest(5,'price');
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## Задание 4
#### Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
#### author_name, min_price, max_price и mean_price,
#### в которых должны содержаться соответственно имя автора,минимальная, максимальная и средняя цена на книги этого автора.

##### первый вариант

In [312]:
#%%timeit
# 6.62 ms ± 27.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
authors_stat = authors_price.groupby('author_name').agg({'price':('max','min','mean')}).round(2)
authors_stat.rename(columns = {'min':'min_price','max':'max_price','mean':'mean_price'}, inplace=True)
authors_stat.columns = authors_stat.columns.droplevel(0)
authors_stat

max_price  min_price  mean_price
author_name                                  
Островский         370        290      330.00
Тургенев           450        300      366.67
Чехов              500        450      475.00

##### второй вариант

In [313]:
# %%timeit
# 5 ms ± 15.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
authors_stat2 = []
for k,i in enumerate(authors['author_name']):
    authors_stat2.append([authors['author_name'][k],
                      authors_price.loc[authors_price['author_name']==i,'price'].min(),
                      authors_price.loc[authors_price['author_name']==i,'price'].max(),
                      authors_price.loc[authors_price['author_name']==i,'price'].mean()
                     ])
authors_stat2=pd.DataFrame(authors_stat2)
authors_stat2.rename(columns = {0:'author',1:'min_price',2:'max_price',3:'mean_price'}, inplace=True)

authors_stat2

author  min_price  max_price  mean_price
0    Тургенев        300        450  366.666667
1       Чехов        450        500  475.000000
2  Островский        290        370  330.000000

## Задание 5**
#### Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

In [266]:
authors_price['cover']=['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

#### Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.

In [315]:
#?pd.pivot_table
book_info = pd.pivot_table(authors_price[['author_name','price','cover']],index='author_name', dropna=False, columns=['cover'],fill_value='0',aggfunc=np.sum)
# удаляем самый верхний уровень названий столбцов, если он нужен - строчку следует закомментировать
book_info.columns = book_info.columns.droplevel(0)
book_info

cover       мягкая твердая
author_name               
Островский     660       0
Тургенев       650     450
Чехов            0     950

#### Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [314]:
book_info.to_pickle('book_info.pkl')
book_info2 = pd.read_pickle('book_info.pkl')

book_info2

cover       мягкая твердая
author_name               
Островский     660       0
Тургенев       650     450
Чехов            0     950